layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - stars
    - pushed
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
      - arm

social_media:
  telegram: plakna
  github: plakna
  stackoverflow: 780711
  linkedin: niklas-plakolb-a1235a189
  steam: plakna
  trakt: plakna
  youtube: UC7T0f6PpDhFDRvAz4QghXkg
  renault: plakna
  website: http://plakna.at

topics:
  - name: Bees
    web_url: https://bienenforum.com
    image_url: assets/topics/bees.jpg

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/raspberry-pi/raspberry-pi.png

  - name: .NET
    web_url: https://github.com/topics/dotnet
    image_url: https://raw.githubusercontent.com/github/explore/93d8a67084f94b2a444e510199a6e7622e5b09a3/topics/dotnet/dotnet.png

  - name: Business Central
    web_url: https://dynamics.microsoft.com/en-us/business-central/overview/
    image_url: assets/topics/bc.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png

  - name: LaTeX
    web_url: https://github.com/topics/latex
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/latex/latex.png

  - name: Markdown
    web_url: https://github.com/topics/markdown
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/markdown/markdown.png

  - name: Oh My Zsh
    web_url: https://github.com/ohmyzsh/ohmyzsh
    image_url: assets/topics/ohmyzsh.jpg